[[main]]
  identifier = "archive"
  name = "ğŸ“šå½’æ¡£"
  url = "archive"
  weight = 1

[[main]]
  identifier = "categories"
  name = "ğŸ“‚åˆ†ç±»"
  url = "categories"
  weight = 2

[[main]]
  identifier = "tags"
  name = "ğŸ·ï¸æ ‡ç­¾"
  url = "tags"
  weight = 3

#[[main]]
  #parent = "categories"
  #name = "å­¦ä¹ "
  #url = "categories/å­¦ä¹ "
  #weight = 1

#[[main]]
  #parent = "categories"
  #name = "ç¬”è®°"
  #url = "categories/ç¬”è®°"
  #weight = 2

#[[main]]
  #parent = "categories"
  #name = "æ‚è°ˆ"
  #url = "categories/æ‚è°ˆ"
  #weight = 3

# [[main]]
  # identifier = "gallery"
  # name = "ğŸ’¼é¡¹ç›®"
  # url = "gallery"
  # weight = 4
    
[[main]]
  identifier = "about"
  name = "ğŸ™‹â€â™‚ï¸å…³äº"
  url = "about"
  weight = 4