[[main]]
  identifier = "archive"
  name = "ğŸ“šå½’æ¡£"
  url = "archive"
  weight = 1

[[main]]
  identifier = "categories"
  name = "ğŸ“‚åˆ†ç±»"
  url = "categories"
  weight = 2

[[main]]
  identifier = "tags"
  name = "ğŸ·ï¸æ ‡ç­¾"
  url = "tags"
  weight = 3

# [[main]]
  # parent = "categories"
  # name = "åˆ†äº«"
  # url = "categories/åˆ†äº«"

# [[main]]
  # parent = "categories"
  # name = "è®°å½•"
  # url = "categories/è®°å½•"

# [[main]]
  # identifier = "gallery"
  # name = "ğŸ’¼é¡¹ç›®"
  # url = "gallery"
  # weight = 4
    
[[main]]
  identifier = "about"
  name = "ğŸ™‹â€â™‚ï¸å…³äº"
  url = "about"
  weight = 4