logoText = "Kitin's"
logoType = "long" # long, short
logo = true
description = "Kitinçš„ä¸ªäººåšå®¢"
custom_css = []
custom_js = []
useFaviconGenerator = true # https://www.favicon-generator.org/
meta_image = ""
themecolor = ""

themeOptions = ["light", "dark"]
notAllowedTypesInHome = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]
notAllowedTypesInHomeSidebar = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]
notAllowedTypesInArchive = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

viewportSize = "normal" # widest, wider, wide, normal, narrow
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = false
enablePinnedPosts = true
minItemsToShowInTagCloud = 1 # Minimum items to show in tag cloud

# appbar
enableAppbarSearchIcon = false
enableAppbarLangIcon = false

# header
homeHeaderType = "text" # text, img, slide, typewriter
hideHomeHeaderWhenMobile = false

# menu
# showMobileMenuTerms = ["tags", "categories"]

# search
enableSearch = true
enableSearchHighlight = true
searchResultPosition = "main" # side, main
searchContent = true # include content to search index
searchDistance = 100 # fuse option
searchThreshold = 0.4 # 0.0: exact match, 1.0: any match

# body
enableBreadcrumb = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006å¹´1æœˆ" # "2006-01": group by month, "2006": group by year
archivePaginate = 10
paginateWindow = 1
talksPaginate = 10
talksGroupByDate = "2006å¹´1æœˆ"
pubPaginate = 20
writtenTimeIcon = "ğŸ“…"
modifiedTimeIcon = "ğŸ“"
readingTimeIcon = "â°"
authorIcon = "âœï¸"
pagePvIcon = "ğŸ‘€"
pinIcon = "ğŸ“Œ"
tagIcon = "ğŸ·ï¸"
publicationIcon = "ğŸ“š"
typeIcon = "ğŸ¯"

# whoami
myname = "Kitin"
email = "hi@kitin.cn"
whoami = "ä¸€ä¸ªä¸çŸ¥åä½†æ˜¯æ»¡è„‘éªšæ“ä½œçš„è®¾è®¡å¸ˆã€‚å–œæ¬¢æ¢ç´¢æ–°æŠ€æœ¯ï¼Œå¸Œæœ›ä¸æ–­å­¦ä¹ ï¼Œä¸æ–­æ€è€ƒï¼Œä¸æ–­æˆé•¿ã€‚"
bioImageUrl = "/images/whoami/avatar.png"
useGravatar = false
location = "China, Asia"
organization = "Kitin"
link = "https://kitin.cn"

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = false
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "outer" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4", "h5", "h6"]
enableSidebarPostsByOrder = false

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = false
enableThemeChange = true

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = false
busuanziSitePV = false
busuanziPagePV = false

# rss
updatePeriod = "monthly" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false

# comment
enableComment = true
disqus_shortname = ""
commento = false

[telegram]
  enable = false
  siteId = ""
  dataLimit = 5

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[utterances]       # https://utteranc.es/
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments

[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = false
  appId = ''
  appKey = ''
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'hide' 
  placeholder = 'è¯´ç‚¹ä»€ä¹ˆå§...'
  visitor = false

# Waline.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://waline.js.org
[waline]
  enable = true
  ServerURL = 'https://wl.kitin.cn'
  Meta = ['nick', 'mail', 'link']
  PageSize = '10'
  HighLighter = true

[changyan]
  changyanAppid = ""        # Changyan app id             # ç•…è¨€
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # æ¥å¿…åŠ›

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "mailto:hi@kitin.cn"
  phone = ""
  facebook = "https://www.facebook.com/jettwqh"
  twitter = "https://twitter.com/jettwqh"
  github = "https://github.com/jetew"
  stack-overflow = ""
  instagram = ""
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = "https://t.me/jettwqh"
  steam = ""
  weibo = ""
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = ""
  signal = ""
  whatsapp = ""
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""
  google-scholar = ""

[donationOptions]
  enable = false
  alipay = "" 
  wechat = ""
  paypal = ""
  patreon = ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line", "pocket", "feedly", "hatena", "pinterest", "delicious", "google"]
# [[share]]
#  name = "facebook"
#  username = ""
# [[share]]
#  name = "twitter"
# [[share]]
#  name = "linkedin"

[[footerLinks]]
  name = ""
  link = ""
[[footerLinks]]
  name = ""
  link = ""

[icp]
  enableicp = false
  icpLink = ""
  icpLinkText = ""